#!/usr/bin/env sh
# Minimal POSIX sh Python-logging flavored utility. Single file. No dependencies.

set -eu

VERSION=0.1.2

LOGLEVEL="${LOGLEVEL:-3}"

PROGPATH="$(realpath -m "$0")"
PROGNAME="${PROGPATH##*/}"

usage() {
    printf '%s\n' "Usage: $PROGNAME..."
    exit "${1:-0}"
}

# Temporary argparse
if [ "$#" -eq 1 ]; then
    case "$1" in
        -h | --help)
            usage 1
            ;;
        -V | --version)
            printf '%s\n' "$VERSION"
            exit 0
            ;;
    esac
fi

_log_levels() {
    case "$1" in
        -1) printf "DIE" ;;
        0) printf "WARN" ;;
        1) printf "INFO" ;;
        2) printf "DEBUG" ;;
        *) printf "LOG" ;;
    esac
}

_log() {
    level="$1"
    shift

    [ "$LOGLEVEL" -lt "$level" ] && return 0

    printf '%s %b\n' "[$(_log_levels "$level")]" "$*" # >&2

    [ "$level" -eq -1 ] && return 1

    return 0
}

log_msg() {
    # Print a string with default ('\n') or custom '_end' (optional: '$2')

    [ "$LOGLEVEL" -eq -1 ] \
        && return 1

    printf '%b' "$1"
    if [ "$#" -ge 2 ]; then
        printf '%b' "$2"
        return 0
    fi

    printf '\n'
}

log_debug() {
    _log 2 "$*"
}

log_info()  {
    _log 1 "$*"
}

log_warn()  {
    _log 0 "$*"
}

log_die()   {
    _log -1 "$*" >&2
}

# Test:
log_msg "This is a direct message to stderr." " – "
log_msg "See 'log_msg \$2' for pythonic flavor. (LOGLEVEL '-1')"
log_info "Processing data... please wait"
log_debug "Current_value=42, state=READY"
log_warn "Disk space is running low on /var/log"
log_die "Failed to connect to database, exiting"
