#!/usr/bin/env sh
# Minimal POSIX sh Python-logging flavored utility. Single file. No dependencies.

# VERSION=0.1.3

set -eu

PROGPATH="$(realpath -m "$0")"
PROGNAME="${PROGPATH##*/}"

SHLOG_COLOR="${SHLOG_COLOR:-1}"
SHLOG_DISABLED="${SHLOG_DISABLED:= }"
SHLOG_FILE="${SHLOG_FILE:=}"
SHLOG_FORMAT="${SHLOG_FORMAT:-%(asctime)s [%(levelname)s] <%(name)s> %(message)s}"
SHLOG_LEVEL="${SHLOG_LEVEL:-2}"
SHLOG_NAME="${SHLOG_NAME:=main}"
SHLOG_TIME_STRING="%H:%M:%S"

# Keep this as it is: Used as separator byte. Normally never occurs in real message.
_LOG_SEP="$(printf '\036')"

usage() {
    printf '%s\n' "Usage: $PROGNAME..."
    exit "${1:-0}"
}

_log() {
    _level="$1"
    shift

    [ "$SHLOG_LEVEL" -lt "$_level" ] \
        && return 0

    if [ "$_level" -ne -1 ]; then
        _log_is_enabled "$SHLOG_NAME" \
            || return 0
    fi

    _asctime="$(date "+$SHLOG_TIME_STRING")"
    _log_levels "$_level"

    _name_text="$(printf '%s%s%s' "$SHLOG_NAME" "$_LOG_SEP" "$*" | _log_str_esc)"
    _name="${_name_text%%"$_LOG_SEP"*}"
    _text="${_name_text#*"$_LOG_SEP"}"

    _line="$(_log_format "$_asctime" "$_levelname" "$_name" "$_text")"

    if [ "$SHLOG_COLOR" -eq 1 ]; then
        _log_colors "$_level"
        printf '\033[%sm%b\033[0m\n' "$_color" "$_line" >&2
    else
        printf '%b\n' "$_line" >&2
    fi

    [ -n "$SHLOG_FILE" ] \
        && printf '%s\n' "$_line" \
        >> "$SHLOG_FILE"

    [ "$_level" -eq -1 ] \
        && exit 1

    return 0
}

_log_str_esc() {
    sed -e 's/\\/\\\\/g' -e 's/&/\\&/g' -e 's/|/\\|/g'
}

_log_colors() {
    case "$1" in
        -1) _color=31 ;;
        0)  _color=35 ;;
        1)  _color=33 ;;
        2)  _color=32 ;;
        *)  _color=0  ;;
    esac
}

_log_format() {
    printf '%s' "$SHLOG_FORMAT" | sed \
        -e "s|%(name)s|$3|g" \
        -e "s|%(message)s|$4|g" \
        -e "s|%(asctime)s|$1|g" \
        -e "s|%(levelname)s|$2|g" \
        -e "s|%(levelshort)s|${2%"${2#?}"}|g"
}

_log_is_enabled() {
    case "$SHLOG_DISABLED" in
        *" $1 "*) return 1 ;;
        *) return 0 ;;
    esac
}

log_disable() {
    for _n in "$@"; do
        case "$SHLOG_DISABLED" in
            *" $_n "*) ;;
            *) SHLOG_DISABLED="$SHLOG_DISABLED$_n " ;;
        esac
    done
}

log_enable() {
    for _n in "$@"; do
        SHLOG_DISABLED=$(
            printf '%s' "$SHLOG_DISABLED" \
                | sed "s/ $_n / /g"
            )
        done
}

_log_levels() {
    case "$1" in
        -1) _levelname="${SHLOG_LEVEL_CRITICAL:-CRITICAL}" ;;
        0) _levelname="${SHLOG_LEVEL_WARNING:-WARNING}" ;;
        1) _levelname="${SHLOG_LEVEL_INFO:-INFO}" ;;
        2) _levelname="${SHLOG_LEVEL_DEBUG:-DEBUG}" ;;
        *) _levelname="${SHLOG_LEVEL_SHLOG:-SHLOG}" ;;
    esac
}

log_name() {
    SHLOG_NAME="${1:-$SHLOG_NAME}"
}

log_msg() {
    [ "$SHLOG_LEVEL" -eq -1 ] \
        && return 1

    printf '%b' "$1"

    if [ "$#" -ge 2 ]; then
        printf '%b' "$2"
        return 0
    fi

    printf '\n'
}

log_die() {
    _log -1 "$*"
}

log_warn() {
    _log 0 "$*"
}

log_info() {
    _log 1 "$*"
}

log_debug() {
    _log 2 "$*"
}

# Test:
log_msg "This is a direct message to stderr."
log_info "Processing data... please wait"
log_debug '{ "user_id": 1, "id": 1, "name": "John" }'
log_warn "Disk space is running low on /var/log"
log_die "Failed to connect to database"
